cameras:
  - id: "cam-01"
    name: "火器营桥卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live1"
    longitude: 116.289
    latitude: 39.985
  - id: "cam-02"
    name: "万泉河桥卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live2"
    longitude: 116.297
    latitude: 39.985
  - id: "cam-03"
    name: "海淀桥西卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live3"
    longitude: 116.308
    latitude: 39.985
  - id: "cam-04"
    name: "中关村方向卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live4"
    longitude: 116.311
    latitude: 39.985
  - id: "cam-05"
    name: "中关村一桥东卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live5"
    longitude: 116.322
    latitude: 39.985
  - id: "cam-06"
    name: "保福寺桥西卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live6"
    longitude: 116.328
    latitude: 39.985
  - id: "cam-07"
    name: "学院桥西卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live7"
    longitude: 116.344
    latitude: 39.985
  - id: "cam-08"
    name: "中关村南卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live8"
    longitude: 116.315
    latitude: 39.967
  - id: "cam-09"
    name: "海淀黄庄卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live9"
    longitude: 116.314
    latitude: 39.980
  - id: "cam-10"
    name: "中关村北大街卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live10"
    longitude: 116.312
    latitude: 39.989
  - id: "cam-11"
    name: "清华西门卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live11"
    longitude: 116.308
    latitude: 39.994
  - id: "cam-12"
    name: "北太平庄卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live12"
    longitude: 116.357
    latitude: 39.961
  - id: "cam-13"
    name: "学知桥卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live13"
    longitude: 116.354
    latitude: 39.969
  - id: "cam-14"
    name: "学院路中段卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live14"
    longitude: 116.352
    latitude: 39.981
  - id: "cam-15"
    name: "学院路北段卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live15"
    longitude: 116.352
    latitude: 39.989
  - id: "cam-16"
    name: "北沙滩南卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live16"
    longitude: 116.355
    latitude: 39.997
  - id: "cam-17"
    name: "万泉河路卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live17"
    longitude: 116.293
    latitude: 39.978
  - id: "cam-18"
    name: "昆明湖卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live18"
    longitude: 116.284
    latitude: 39.989
  - id: "cam-19"
    name: "长春桥卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live19"
    longitude: 116.285
    latitude: 39.977
  - id: "cam-20"
    name: "中关园卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live20"
    longitude: 116.324
    latitude: 39.992
  - id: "cam-21"
    name: "五道口卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live21"
    longitude: 116.345
    latitude: 39.993
  - id: "cam-22"
    name: "知春路西卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live22"
    longitude: 116.324
    latitude: 39.980
  - id: "cam-23"
    name: "知春路东卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live23"
    longitude: 116.344
    latitude: 39.981
  - id: "cam-24"
    name: "海淀桥北卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live24"
    longitude: 116.304
    latitude: 39.996
  - id: "cam-25"
    name: "上地南卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live25"
    longitude: 116.303
    latitude: 40.007
  - id: "cam-26"
    name: "上地三街卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live26"
    longitude: 116.303
    latitude: 40.024
  - id: "cam-27"
    name: "上地五街卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live27"
    longitude: 116.303
    latitude: 40.031
  - id: "cam-28"
    name: "西二旗大街卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live28"
    longitude: 116.305
    latitude: 40.044
  - id: "cam-29"
    name: "八达岭高速南卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live29"
    longitude: 116.355
    latitude: 39.993
  - id: "cam-30"
    name: "清河大桥卡口"
    url: "rtsp://10.126.59.120:8554/liveDemo/live30"
    longitude: 116.357
    latitude: 40.018